10-01 16:38 errLogger    ERROR    Face list resizing error
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 25, in calculate_faces
    face_array = self.resize_images(face_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 44, in resize_images
    tmp_face = cv2.resize(face, dsize=(160, 160))
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

10-01 16:38 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 204, in process
    scan_dist = self.count_distance(video_face_hash, scan_face_hash)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 215, in count_distance
    dist = distance.euclidean(hash_1, hash_2)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 620, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 512, in minkowski
    u_v = u - v
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
10-01 16:38 errLogger    ERROR    Face list resizing error
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 25, in calculate_faces
    face_array = self.resize_images(face_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 44, in resize_images
    tmp_face = cv2.resize(face, dsize=(160, 160))
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

10-01 16:38 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 204, in process
    scan_dist = self.count_distance(video_face_hash, scan_face_hash)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 215, in count_distance
    dist = distance.euclidean(hash_1, hash_2)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 620, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 512, in minkowski
    u_v = u - v
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
10-01 16:39 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 191, in process
    cv2.imshow('window_name', frame)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

10-01 16:40 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 191, in process
    cv2.imshow('window_name', frame)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

10-01 16:42 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 191, in process
    cv2.imshow('window_name', frame)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

10-01 16:44 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 192, in process
    cv2.imshow('window_name', frame)
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'

10-01 16:46 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 190, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 164, in get_faces
    while len(frame_list) > 0:
TypeError: object of type 'NoneType' has no len()
10-01 16:49 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 190, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 164, in get_faces
    while len(frame_list) > 0:
TypeError: object of type 'NoneType' has no len()
10-01 16:51 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 191, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 165, in get_faces
    while len(frame_list) > 0:
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:54 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 187, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 16:56 errLogger    ERROR    Model or face crop failure
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\detector.py", line 53, in detect
    print(face.shape)
AttributeError: 'list' object has no attribute 'shape'
10-01 16:56 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 193, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 173, in get_faces
    face_list = face_list + face_batch
TypeError: can only concatenate list (not "NoneType") to list
10-01 16:56 errLogger    ERROR    Model or face crop failure
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\detector.py", line 53, in detect
    print(face.shape)
AttributeError: 'list' object has no attribute 'shape'
10-01 16:56 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 193, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 173, in get_faces
    face_list = face_list + face_batch
TypeError: can only concatenate list (not "NoneType") to list
10-01 16:58 errLogger    ERROR    Face list resizing error
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 25, in calculate_faces
    face_array = self.resize_images(face_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 44, in resize_images
    tmp_face = cv2.resize(face, dsize=(160, 160))
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

10-01 16:58 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 209, in process
    scan_dist = self.count_distance(video_face_hash, scan_face_hash)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 220, in count_distance
    dist = distance.euclidean(hash_1, hash_2)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 620, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 512, in minkowski
    u_v = u - v
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:03 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:04 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:05 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 194, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 166, in get_faces
    while len(frame_list) > 0:
TypeError: object of type 'NoneType' has no len()
10-01 17:06 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 194, in process
    video_face_list = self.get_faces(frame_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 166, in get_faces
    while len(frame_list) > 0:
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:07 errLogger    ERROR    Cannot read video file face_video_3.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:08 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:14 errLogger    ERROR    Cannot read video file face_video_2.avi
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 188, in process
    print(len(frame_list))
TypeError: object of type 'NoneType' has no len()
10-01 17:25 errLogger    ERROR    Face list resizing error
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 25, in calculate_faces
    face_array = self.resize_images(face_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 44, in resize_images
    tmp_face = cv2.resize(face, dsize=(160, 160))
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

10-01 17:25 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 208, in process
    scan_dist = self.count_distance(video_face_hash, scan_face_hash)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 219, in count_distance
    dist = distance.euclidean(hash_1, hash_2)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 620, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 512, in minkowski
    u_v = u - v
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
10-01 17:35 errLogger    ERROR    Face list resizing error
Traceback (most recent call last):
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 25, in calculate_faces
    face_array = self.resize_images(face_list)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\utils\calculate_face.py", line 44, in resize_images
    tmp_face = cv2.resize(face, dsize=(160, 160))
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3929: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

10-01 17:35 errLogger    ERROR    Error: Video_processing starting fail
Traceback (most recent call last):
  File "D:/Py_Work/PyProj/frontier_fase_recognition/main.py", line 8, in main
    streamer.process()
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 207, in process
    scan_dist = self.count_distance(video_face_hash, scan_face_hash)
  File "D:\Py_Work\PyProj\frontier_fase_recognition\person_processing.py", line 218, in count_distance
    dist = distance.euclidean(hash_1, hash_2)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 620, in euclidean
    return minkowski(u, v, p=2, w=w)
  File "D:\Python\envs\Functions\lib\site-packages\scipy\spatial\distance.py", line 512, in minkowski
    u_v = u - v
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
